pipeline {
	agent { 
		docker {
			image 'node:16.20.0-alpine' 
			args '-u root:root --network=office-lab_jenkins-network'
			// args '--tmpfs /usr'
		} 
	}
	stages {
		// stage('Hosts file') {
		// 	steps {
		// 		sh 'cat /etc/hosts'
		// 	}
		// }
		stage('Installing SonaQube Scanner') {
			steps {
				sh 'apk update'
				sh 'apk add --no-cache openjdk17-jre'
				// sh 'curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip -o sonar-scanner.zip'
				sh 'apk add --no-cache \
  					ca-certificates \
  					curl'
				sh 'mkdir -p /opt'
				sh 'curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856.zip -o /opt/sonar-scanner.zip'
				sh 'unzip /opt/sonar-scanner.zip -d /opt'
				sh 'rm /opt/sonar-scanner.zip'
				sh 'ln -s /opt/sonar-scanner-4.8.0.2856/bin/sonar-scanner /usr/bin/sonar-scanner'
			}
		}
		stage('Starting the SonarQube Scan...') {
			steps {
				withCredentials([string(credentialsId: 'sonar-key', variable: "SONAR_KEY")]) {
					sh 'sonar-scanner \
						-Dsonar.exclusions="**/node_modules/**/*,**/*.spec.ts" \
  						-Dsonar.projectKey=hadiya-frontend \
  						-Dsonar.sources=. \
						-Dsonar.projectVersion=0.1 \
  						-Dsonar.host.url=http://sonar:9000 \
  						-Dsonar.token=$SONAR_KEY'
				}
			}
		}
		stage('Cleaning Cache...') {
			steps {
				// sh 'npm install -g npm@latest'
				sh 'npm cache clean --force'
			}
		}
		stage('Installing Depedencies...') {
			steps {
				// sh 'cd products_admin'
				// sh 'pwd'
				sh 'npm install -g @angular/cli'
				sh 'npm install'
				// sh 'ls'
				// sh 'wtf'
			}
		}
		stage('Building the code...') {
			steps {
				sh 'ng build'
			}
		}
	}
	post {
		success {
			slackSend color: '#36a64f', message: "Pipeline \"hadiya-frontend\" executed successfully!"
			archiveArtifacts artifacts: 'dist/hadiya_products_admin/*', 
			onlyIfSuccessful: true
		}
		failure {
      		slackSend color: '#ff0000', message: "Pipeline \"hadiya-frontend\" Failed!"
    	}
	}
}
